name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
      - name: Rebase the nightly_master and nightly_dev branches
        run: |
          cd  ${{ github.workspace }}
          git checkout nightly_master
          git rebase origin/master
          git push origin nightly_master
          git checkout nightly_dev
          git rebase origin/dev
          git push origin nightly_dev
      - run: echo " This job's status is ${{ job.status }}."
